[build]
  # This will be run the site build
  # command = "npm run build:functions"
  # This is the directory is publishing to netlify's CDN
  # and this is directory of your front of your app
  publish = "src"

[functions]
	directory = "functions"
	node_bundler = "esbuild" 
	included_files = ["src/static/**", "src/views/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
